# Purpose: Docker Compose configuration for Confuror Calendar app
# Context: Defines services for the app (now CSV-based, no database required)

version: '3.8'

services:
  # Confuror Calendar App
  app:
    image: windowsagent/pawsistente:v0.3.9-alpha
    container_name: pawsistente-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    networks:
      - pawsistente-network
    volumes:
      - ./static:/app/static:ro

networks:
  pawsistente-network:
    driver: bridge
